---
title: "Individual Project Proposal"
author: "Olivia Gomez"
format: pdf
editor: visual
---

# Individual Project Proposal

In my final project, I would like to explore if a rise in anti-immigration rhetoric across the country in recent years has impacted health outcomes for immigrant populations. I would like to use a larger data, like the National Health Interview Survey, to ensure I am analyzing data from the same individuals over time. To measure anti-immigration rhetoric, I plan on using the Annual National Election Studies which survey individuals on voting behavior, public opinion, and attitudes and is conducted every year, so trends can be evaluated. To measure health outcomes, health insurance status can be a good proxy for overall health, as those who have access to care through insurance typically have better outcomes overall. I would like to especially see if there are trends in areas with large immigrant populations, like the American south and larger cities such as New York and Chicago.
